name = "urlshortener"

main = "src/app.ts"
compatibility_date = "2022-05-28"
workers_dev = true
account_id = "29290f0059a332e257b2d87799eff855"
route = "short.yoshualopez.com/*"


kv_namespaces = [
  { binding = "SHORTS", id = "c14d521785e44dd8a06d9efdcb95e10e" }
]
